version: "3"

services:
  postgres:
    image: postgres:latest
    container_name: db-dev
    restart: always
    env_file:
      - .env
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    volumes:
      - ${DB_DATA}/pgdata:/var/lib/postgresql/data
      - ${DB_MIG}:/migrations
      - ${DB_BIN}:/usr_bin
      - ${DB_SEED}:/seed
    ports:
      - "${DB_PORT}:5432"
    entrypoint: ["/usr_bin/init"]

  # postgres_test:
  #   image: postgres:latest
  #   container_name: test_postgres
  #   env_file:
  #     - .env
  #   environment:
  #     POSTGRES_USER: ${TEST_DB_USER}
  #     POSTGRES_PASSWORD: ${TEST_DB_PASSWORD}
  #     POSTGRES_DB: ${TEST_DB_NAME}
  #   ports:
  #     - "${TEST_DB_PORT}:5432"
  #   volumes:
  #     - ${DB_MIG}:/docker-entrypoint-initdb.d  # Auto-run migrations
  #     - ${DB_DATA}/pgtestdata:/var/lib/postgresql/data
