#!/bin/zsh

# Define the help function before it's called
function help() {
  echo "Usage: $0 <command>"
  echo "Commands:"
  echo "  start - build and start the test server"
  echo "  clean - remove the test server binary"
  echo "  tidy - run go mod tidy and vendor"
  echo "  install <package> - install a package and run go mod tidy and vendor"
  echo "  help - show this help message"
  exit 0
}

# If no command is specified, show help
if [ -z "$1" ]; then
  help
fi

# Handle commands
case "$1" in 
  help)
    help
    ;;
  tree)
    tree --gitignore
    ;;
  start)
    go mod tidy
    go mod vendor
    go build -o go-webapp src/main.go
    ./go-webapp
    ;;
  clean)
    rm -f test-server
    ;;
  tidy)
    go mod tidy
    go mod vendor
    ;;
  install)
    if [ -z "$2" ]; then
      echo "Usage: $0 install <package>"
      exit 1
    fi
    go get $2
    go mod tidy
    go mod vendor
    ;;
  i)
    if [ -z "$2" ]; then
      echo "Usage: $0 install <package>"
      exit 1
    fi
    go get $2
    go mod tidy
    go mod vendor
    ;;
  *)
    echo "Unknown command: $1"
    exit 1
    ;;
esac

exit 0
