// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0

package libdb

import (
	"database/sql"
	"time"

	"github.com/google/uuid"
	"github.com/sqlc-dev/pqtype"
)

type ActiveTask struct {
	ID               uuid.UUID
	Name             string
	Description      string
	ProjectID        uuid.NullUUID
	AssigneeUsername string
	AssignerUsername string
	Status           string
	Priority         string
	AssignedAt       time.Time
	StartAt          time.Time
	EstimatedHours   int32
	ActualHours      int32
	Type             string
	CreatedAt        time.Time
	ModifiedAt       time.Time
	Protected        bool
	Inactive         bool
	DeletedAt        sql.NullTime
}

type Appointment struct {
	ID                uuid.UUID
	Name              string
	Description       string
	OrganizerUsername string
	Type              string
	ScheduledAt       time.Time
	DurationMinutes   int32
	Location          string
	Status            string
	DepartmentID      uuid.NullUUID
	CreatedAt         time.Time
	ModifiedAt        time.Time
	Protected         bool
	Inactive          bool
	DeletedAt         sql.NullTime
}

type AppointmentIdentity struct {
	ID               uuid.UUID
	AppointmentID    uuid.UUID
	IdentityUsername string
	CreatedAt        time.Time
	ModifiedAt       time.Time
	Protected        bool
	Inactive         bool
	DeletedAt        sql.NullTime
}

type Department struct {
	ID              uuid.UUID
	Name            string
	Description     string
	ManagerUsername string
	CreatedAt       time.Time
	ModifiedAt      time.Time
	Protected       bool
	Inactive        bool
	DeletedAt       sql.NullTime
}

type Identity struct {
	ID              uuid.UUID
	Username        string
	FirstName       sql.NullString
	LastName        sql.NullString
	Email           string
	IsManager       bool
	ManagerUsername sql.NullString
	Details         pqtype.NullRawMessage
	Designation     sql.NullString
	PasswordHash    []byte
	CreatedAt       time.Time
	ModifiedAt      time.Time
	Protected       bool
	Inactive        bool
	DeletedAt       sql.NullTime
}

type IdentityPermission struct {
	ID               uuid.UUID
	IdentityUsername string
	PermissionID     uuid.UUID
	CreatedAt        time.Time
	ModifiedAt       time.Time
	Protected        bool
	Inactive         bool
	DeletedAt        sql.NullTime
}

type IdentityRole struct {
	ID               uuid.UUID
	IdentityUsername string
	RoleID           uuid.UUID
	CreatedAt        time.Time
	ModifiedAt       time.Time
	Protected        bool
	Inactive         bool
	DeletedAt        sql.NullTime
}

type LeaveTable struct {
	ID                uuid.UUID
	ApplicantUsername string
	ApproverUsername  string
	Reason            string
	Type              string
	StartDate         time.Time
	Hours             int32
	Status            string
	CreatedAt         time.Time
	ModifiedAt        time.Time
	Protected         bool
	Inactive          bool
	DeletedAt         sql.NullTime
}

type Permission struct {
	ID          uuid.UUID
	Name        string
	Description string
	CreatedAt   time.Time
	ModifiedAt  time.Time
	Protected   bool
	Inactive    bool
	DeletedAt   sql.NullTime
}

type PermissionResource struct {
	ID           uuid.UUID
	PermissionID uuid.UUID
	ResourceID   uuid.UUID
	CreatedAt    time.Time
	ModifiedAt   time.Time
	Protected    bool
	Inactive     bool
	DeletedAt    sql.NullTime
}

type Project struct {
	ID              uuid.UUID
	Name            string
	Description     string
	ManagerUsername sql.NullString
	DepartmentID    uuid.NullUUID
	StartDate       time.Time
	EndDate         sql.NullTime
	Status          string
	Priority        string
	CreatedAt       time.Time
	ModifiedAt      time.Time
	Protected       bool
	Inactive        bool
	DeletedAt       sql.NullTime
}

type ProjectIdentity struct {
	ID               uuid.UUID
	ProjectID        uuid.UUID
	IdentityUsername string
	CreatedAt        time.Time
	ModifiedAt       time.Time
	Protected        bool
	Inactive         bool
	DeletedAt        sql.NullTime
}

type ProjectTask struct {
	ID         uuid.UUID
	ProjectID  uuid.UUID
	TaskID     uuid.UUID
	CreatedAt  time.Time
	ModifiedAt time.Time
	Protected  bool
	Inactive   bool
	DeletedAt  sql.NullTime
}

type Resource struct {
	ID          uuid.UUID
	Name        string
	Description string
	Operation   string
	Endpoint    string
	CreatedAt   time.Time
	ModifiedAt  time.Time
	Protected   bool
	Inactive    bool
	DeletedAt   sql.NullTime
}

type Role struct {
	ID          uuid.UUID
	Name        string
	Description string
	CreatedAt   time.Time
	ModifiedAt  time.Time
	Protected   bool
	Inactive    bool
	DeletedAt   sql.NullTime
}

type RolePermission struct {
	ID           uuid.UUID
	RoleID       uuid.UUID
	PermissionID uuid.UUID
	CreatedAt    time.Time
	ModifiedAt   time.Time
	Protected    bool
	Inactive     bool
	DeletedAt    sql.NullTime
}

type Task struct {
	ID               uuid.UUID
	Name             string
	Description      string
	ProjectID        uuid.NullUUID
	AssigneeUsername string
	AssignerUsername string
	Status           string
	Priority         string
	AssignedAt       time.Time
	StartAt          time.Time
	EstimatedHours   int32
	ActualHours      int32
	Type             string
	CreatedAt        time.Time
	ModifiedAt       time.Time
	Protected        bool
	Inactive         bool
	DeletedAt        sql.NullTime
}

type VAppointment struct {
	ID                uuid.UUID
	Name              string
	Description       string
	OrganizerUsername string
	Type              string
	ScheduledAt       time.Time
	DurationMinutes   int32
	Location          string
	Status            string
	DepartmentID      uuid.NullUUID
	CreatedAt         time.Time
	ModifiedAt        time.Time
	Protected         bool
	Inactive          bool
	DeletedAt         sql.NullTime
}

type VAppointmentIdentity struct {
	ID               uuid.UUID
	AppointmentID    uuid.UUID
	IdentityUsername string
	CreatedAt        time.Time
	ModifiedAt       time.Time
	Protected        bool
	Inactive         bool
	DeletedAt        sql.NullTime
}

type VDepartment struct {
	ID              uuid.UUID
	Name            string
	Description     string
	ManagerUsername string
	CreatedAt       time.Time
	ModifiedAt      time.Time
	Protected       bool
	Inactive        bool
	DeletedAt       sql.NullTime
}

type VIdentity struct {
	ID              uuid.UUID
	Username        string
	FirstName       sql.NullString
	LastName        sql.NullString
	Email           string
	IsManager       bool
	ManagerUsername sql.NullString
	Details         pqtype.NullRawMessage
	Designation     sql.NullString
	PasswordHash    []byte
	CreatedAt       time.Time
	ModifiedAt      time.Time
	Protected       bool
	Inactive        bool
	DeletedAt       sql.NullTime
}

type VIdentityPermission struct {
	ID               uuid.UUID
	IdentityUsername string
	PermissionID     uuid.UUID
	CreatedAt        time.Time
	ModifiedAt       time.Time
	Protected        bool
	Inactive         bool
	DeletedAt        sql.NullTime
}

type VIdentityRole struct {
	ID               uuid.UUID
	IdentityUsername string
	RoleID           uuid.UUID
	CreatedAt        time.Time
	ModifiedAt       time.Time
	Protected        bool
	Inactive         bool
	DeletedAt        sql.NullTime
}

type VLeaveTable struct {
	ID                uuid.UUID
	ApplicantUsername string
	ApproverUsername  string
	Reason            string
	Type              string
	StartDate         time.Time
	Hours             int32
	Status            string
	CreatedAt         time.Time
	ModifiedAt        time.Time
	Protected         bool
	Inactive          bool
	DeletedAt         sql.NullTime
}

type VPermission struct {
	ID          uuid.UUID
	Name        string
	Description string
	CreatedAt   time.Time
	ModifiedAt  time.Time
	Protected   bool
	Inactive    bool
	DeletedAt   sql.NullTime
}

type VPermissionResource struct {
	ID           uuid.UUID
	PermissionID uuid.UUID
	ResourceID   uuid.UUID
	CreatedAt    time.Time
	ModifiedAt   time.Time
	Protected    bool
	Inactive     bool
	DeletedAt    sql.NullTime
}

type VProject struct {
	ID              uuid.UUID
	Name            string
	Description     string
	ManagerUsername sql.NullString
	DepartmentID    uuid.NullUUID
	StartDate       time.Time
	EndDate         sql.NullTime
	Status          string
	Priority        string
	CreatedAt       time.Time
	ModifiedAt      time.Time
	Protected       bool
	Inactive        bool
	DeletedAt       sql.NullTime
}

type VProjectIdentity struct {
	ID               uuid.UUID
	ProjectID        uuid.UUID
	IdentityUsername string
	CreatedAt        time.Time
	ModifiedAt       time.Time
	Protected        bool
	Inactive         bool
	DeletedAt        sql.NullTime
}

type VProjectTask struct {
	ID         uuid.UUID
	ProjectID  uuid.UUID
	TaskID     uuid.UUID
	CreatedAt  time.Time
	ModifiedAt time.Time
	Protected  bool
	Inactive   bool
	DeletedAt  sql.NullTime
}

type VResource struct {
	ID          uuid.UUID
	Name        string
	Description string
	Operation   string
	Endpoint    string
	CreatedAt   time.Time
	ModifiedAt  time.Time
	Protected   bool
	Inactive    bool
	DeletedAt   sql.NullTime
}

type VRole struct {
	ID          uuid.UUID
	Name        string
	Description string
	CreatedAt   time.Time
	ModifiedAt  time.Time
	Protected   bool
	Inactive    bool
	DeletedAt   sql.NullTime
}

type VRolePermission struct {
	ID           uuid.UUID
	RoleID       uuid.UUID
	PermissionID uuid.UUID
	CreatedAt    time.Time
	ModifiedAt   time.Time
	Protected    bool
	Inactive     bool
	DeletedAt    sql.NullTime
}

type VViolation struct {
	ID                   uuid.UUID
	PerpetratorUsername  string
	Description          string
	ReporterUsername     string
	InvestigatorUsername sql.NullString
	Type                 string
	Severity             string
	Date                 time.Time
	Status               string
	Action               sql.NullString
	MonetaryPenalty      sql.NullString
	ResolutionDate       sql.NullTime
	CreatedAt            time.Time
	ModifiedAt           time.Time
	Protected            bool
	Inactive             bool
	DeletedAt            sql.NullTime
}

type Violation struct {
	ID                   uuid.UUID
	PerpetratorUsername  string
	Description          string
	ReporterUsername     string
	InvestigatorUsername sql.NullString
	Type                 string
	Severity             string
	Date                 time.Time
	Status               string
	Action               sql.NullString
	MonetaryPenalty      sql.NullString
	ResolutionDate       sql.NullTime
	CreatedAt            time.Time
	ModifiedAt           time.Time
	Protected            bool
	Inactive             bool
	DeletedAt            sql.NullTime
}
